# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class NumericalIndex(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, has_standard_variable=None, description=None, id=None, label=None, type=None):  # noqa: E501
        """NumericalIndex - a model defined in OpenAPI

        :param has_standard_variable: The has_standard_variable of this NumericalIndex.  # noqa: E501
        :type has_standard_variable: List[StandardVariable]
        :param description: The description of this NumericalIndex.  # noqa: E501
        :type description: List[str]
        :param id: The id of this NumericalIndex.  # noqa: E501
        :type id: str
        :param label: The label of this NumericalIndex.  # noqa: E501
        :type label: List[str]
        :param type: The type of this NumericalIndex.  # noqa: E501
        :type type: List[str]
        """
        from openapi_server.models.standard_variable import StandardVariable

          # noqa: E501

        self.openapi_types = {
            'has_standard_variable': List[StandardVariable],
            'description': List[str],
            'id': str,
            'label': List[str],
            'type': List[str]
        }

        self.attribute_map = {
            'has_standard_variable': 'hasStandardVariable',
            'description': 'description',
            'id': 'id',
            'label': 'label',
            'type': 'type'
        }

        self._has_standard_variable = has_standard_variable
        self._description = description
        self._id = id
        self._label = label
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'NumericalIndex':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NumericalIndex of this NumericalIndex.  # noqa: E501
        :rtype: NumericalIndex
        """
        return util.deserialize_model(dikt, cls)

    @property
    def has_standard_variable(self):
        """Gets the has_standard_variable of this NumericalIndex.

        the standard name of a variable  # noqa: E501

        :return: The has_standard_variable of this NumericalIndex.
        :rtype: List[StandardVariable]
        """
        return self._has_standard_variable

    @has_standard_variable.setter
    def has_standard_variable(self, has_standard_variable):
        """Sets the has_standard_variable of this NumericalIndex.

        the standard name of a variable  # noqa: E501

        :param has_standard_variable: The has_standard_variable of this NumericalIndex.
        :type has_standard_variable: List[StandardVariable]
        """

        self._has_standard_variable = has_standard_variable

    @property
    def description(self):
        """Gets the description of this NumericalIndex.

        small description  # noqa: E501

        :return: The description of this NumericalIndex.
        :rtype: List[str]
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this NumericalIndex.

        small description  # noqa: E501

        :param description: The description of this NumericalIndex.
        :type description: List[str]
        """

        self._description = description

    @property
    def id(self):
        """Gets the id of this NumericalIndex.

        identifier  # noqa: E501

        :return: The id of this NumericalIndex.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this NumericalIndex.

        identifier  # noqa: E501

        :param id: The id of this NumericalIndex.
        :type id: str
        """

        self._id = id

    @property
    def label(self):
        """Gets the label of this NumericalIndex.

        short description of the resource  # noqa: E501

        :return: The label of this NumericalIndex.
        :rtype: List[str]
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this NumericalIndex.

        short description of the resource  # noqa: E501

        :param label: The label of this NumericalIndex.
        :type label: List[str]
        """

        self._label = label

    @property
    def type(self):
        """Gets the type of this NumericalIndex.

        type of the resource  # noqa: E501

        :return: The type of this NumericalIndex.
        :rtype: List[str]
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this NumericalIndex.

        type of the resource  # noqa: E501

        :param type: The type of this NumericalIndex.
        :type type: List[str]
        """

        self._type = type
