version: '3'
services:
  api:
    image: "mintproject/model-catalog-api"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
  swagger-ui:
    image: mosoriob/swagger-ui
    build:
      context: .
      dockerfile: Dockerfile_swagger_ui
    volumes:
      - "./:/tmp/"
  endpoint:
    image: mintproject/fuseki-docker:3.8.0
    env_file:
      - .env
    volumes:
      - databases:/fuseki-base/databases/
volumes:
  databases:
