version: '3'
services:
  dev:
    image: "mintproject/model-catalog-api:tacc"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

  endpoint:
    image: fuseki
    env_file:
      - .env
  
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "${SWAGGER_PORT}:8080"
    volumes:
      - "./:/tmp/"
    environment:
      SWAGGER_JSON: "/tmp/openapi.json"
      BASE_URL: "/v1.7.0/ui"
