version: '3'
services:
  api:
    image: "mintproject/model-catalog-api"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
  docs:
    image: mintproject/swagger-ui
    environment:
      SWAGGER_JSON: "/tmp/openapi.json"
      BASE_URL: "/v1.8.0/ui"
    ports:
      - 8081:8080