#+ summary: Given a rdf type, returns all the resources related to the type
CONSTRUCT {
    ?model ?predicate ?prop .
    ?prop a ?type
}
WHERE {
    GRAPH ?_g_iri {
        ?model a ?type.
        ?model sdm:usefulForCalculatingIndex ?index .
        ?index rdfs:label ?indexLabel
        FILTER REGEX(?indexLabel, ?_label)
        VALUES ?type {sdm:Model sdm:ModelConfiguration sdm:ModelConfigurationSetup}
        ?model ?predicate ?prop
        OPTIONAL {
         ?prop a ?type
        }
    }
}